

name: Build and deploy Python app to Azure Web App - P5-tags

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: download nltk
        run: python -m dowload_nltk.py

      - name: pytest
        run: pytest test_final_model.py

    
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      
          
